// Code generated by protoc-gen-go. DO NOT EDIT.
// source: vessel.proto

/*
Package vessel is a generated protocol buffer package.

It is generated from these files:
	vessel.proto

It has these top-level messages:
	Vessel
	Specification
	Response
*/
package vessel

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 代销信息对象
type Vessel struct {
	Id        string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Capacity  int32  `protobuf:"varint,2,opt,name=capacity" json:"capacity,omitempty"`
	MaxWeight int32  `protobuf:"varint,3,opt,name=max_weight,json=maxWeight" json:"max_weight,omitempty"`
	Name      string `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	Available bool   `protobuf:"varint,5,opt,name=available" json:"available,omitempty"`
	OwnerId   string `protobuf:"bytes,6,opt,name=owner_id,json=ownerId" json:"owner_id,omitempty"`
}

func (m *Vessel) Reset()                    { *m = Vessel{} }
func (m *Vessel) String() string            { return proto.CompactTextString(m) }
func (*Vessel) ProtoMessage()               {}
func (*Vessel) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Vessel) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Vessel) GetCapacity() int32 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *Vessel) GetMaxWeight() int32 {
	if m != nil {
		return m.MaxWeight
	}
	return 0
}

func (m *Vessel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Vessel) GetAvailable() bool {
	if m != nil {
		return m.Available
	}
	return false
}

func (m *Vessel) GetOwnerId() string {
	if m != nil {
		return m.OwnerId
	}
	return ""
}

type Specification struct {
	Capacity  int32 `protobuf:"varint,1,opt,name=capacity" json:"capacity,omitempty"`
	MaxWeight int32 `protobuf:"varint,2,opt,name=max_weight,json=maxWeight" json:"max_weight,omitempty"`
}

func (m *Specification) Reset()                    { *m = Specification{} }
func (m *Specification) String() string            { return proto.CompactTextString(m) }
func (*Specification) ProtoMessage()               {}
func (*Specification) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Specification) GetCapacity() int32 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *Specification) GetMaxWeight() int32 {
	if m != nil {
		return m.MaxWeight
	}
	return 0
}

// 响应对象
type Response struct {
	Vessel  *Vessel   `protobuf:"bytes,1,opt,name=vessel" json:"vessel,omitempty"`
	Vessels []*Vessel `protobuf:"bytes,2,rep,name=vessels" json:"vessels,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Response) GetVessel() *Vessel {
	if m != nil {
		return m.Vessel
	}
	return nil
}

func (m *Response) GetVessels() []*Vessel {
	if m != nil {
		return m.Vessels
	}
	return nil
}

func init() {
	proto.RegisterType((*Vessel)(nil), "vessel.Vessel")
	proto.RegisterType((*Specification)(nil), "vessel.Specification")
	proto.RegisterType((*Response)(nil), "vessel.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for VesselService service

type VesselServiceClient interface {
	FindAvailable(ctx context.Context, in *Specification, opts ...client.CallOption) (*Response, error)
}

type vesselServiceClient struct {
	c           client.Client
	serviceName string
}

func NewVesselServiceClient(serviceName string, c client.Client) VesselServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "vessel"
	}
	return &vesselServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *vesselServiceClient) FindAvailable(ctx context.Context, in *Specification, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "VesselService.FindAvailable", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for VesselService service

type VesselServiceHandler interface {
	FindAvailable(context.Context, *Specification, *Response) error
}

func RegisterVesselServiceHandler(s server.Server, hdlr VesselServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&VesselService{hdlr}, opts...))
}

type VesselService struct {
	VesselServiceHandler
}

func (h *VesselService) FindAvailable(ctx context.Context, in *Specification, out *Response) error {
	return h.VesselServiceHandler.FindAvailable(ctx, in, out)
}

func init() { proto.RegisterFile("vessel.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 273 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x51, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x75, 0xd3, 0x36, 0x4d, 0x46, 0x53, 0x64, 0x40, 0x58, 0x8b, 0x42, 0xc8, 0x41, 0x72, 0xea,
	0xa1, 0xde, 0xbc, 0x79, 0x11, 0xd4, 0x5b, 0x0a, 0x7a, 0x11, 0xca, 0x36, 0x19, 0x75, 0x20, 0xc9,
	0x86, 0x6c, 0x48, 0xeb, 0xbf, 0xf1, 0xa7, 0x0a, 0x9b, 0xa4, 0x52, 0x91, 0xde, 0xde, 0xc7, 0xce,
	0xf0, 0xe6, 0x2d, 0x9c, 0xb5, 0x64, 0x0c, 0xe5, 0x8b, 0xaa, 0xd6, 0x8d, 0x46, 0xb7, 0x63, 0xd1,
	0xb7, 0x00, 0xf7, 0xc5, 0x42, 0x9c, 0x81, 0xc3, 0x99, 0x14, 0xa1, 0x88, 0xfd, 0xc4, 0xe1, 0x0c,
	0xe7, 0xe0, 0xa5, 0xaa, 0x52, 0x29, 0x37, 0x5f, 0xd2, 0x09, 0x45, 0x3c, 0x49, 0xf6, 0x1c, 0xaf,
	0x01, 0x0a, 0xb5, 0x5b, 0x6f, 0x89, 0x3f, 0x3e, 0x1b, 0x39, 0xb2, 0xae, 0x5f, 0xa8, 0xdd, 0xab,
	0x15, 0x10, 0x61, 0x5c, 0xaa, 0x82, 0xe4, 0xd8, 0x2e, 0xb3, 0x18, 0xaf, 0xc0, 0x57, 0xad, 0xe2,
	0x5c, 0x6d, 0x72, 0x92, 0x93, 0x50, 0xc4, 0x5e, 0xf2, 0x2b, 0xe0, 0x25, 0x78, 0x7a, 0x5b, 0x52,
	0xbd, 0xe6, 0x4c, 0xba, 0x76, 0x6a, 0x6a, 0xf9, 0x63, 0x16, 0x3d, 0x41, 0xb0, 0xaa, 0x28, 0xe5,
	0x77, 0x4e, 0x55, 0xc3, 0xba, 0x3c, 0x08, 0x26, 0x8e, 0x06, 0x73, 0xfe, 0x04, 0x8b, 0xde, 0xc0,
	0x4b, 0xc8, 0x54, 0xba, 0x34, 0x84, 0x37, 0xd0, 0x97, 0x60, 0x97, 0x9c, 0x2e, 0x67, 0x8b, 0xbe,
	0xa1, 0xae, 0x8f, 0xa4, 0x77, 0x31, 0x86, 0x69, 0x87, 0x8c, 0x74, 0xc2, 0xd1, 0x3f, 0x0f, 0x07,
	0x7b, 0xf9, 0x0c, 0x41, 0x27, 0xad, 0xa8, 0x6e, 0x39, 0x25, 0xbc, 0x83, 0xe0, 0x81, 0xcb, 0xec,
	0x7e, 0x7f, 0xe6, 0xc5, 0x30, 0x7a, 0x70, 0xd1, 0xfc, 0x7c, 0x90, 0x87, 0x70, 0xd1, 0xc9, 0xc6,
	0xb5, 0x1f, 0x75, 0xfb, 0x13, 0x00, 0x00, 0xff, 0xff, 0x49, 0xaa, 0xc6, 0x91, 0xb8, 0x01, 0x00,
	0x00,
}
